"""New AI news sources managed as structured site definitions."""

SOURCES_CONFIG = [
    {
        "name": "DeepSeek",
        "url": "https://deepseek.com/news",
        "kind": "list",
        "parser": "parse_deepseek_news",
        "country": "domestic",
        "timeout": 10,
        "verify": True,
    },
    {
        "name": "Kimi (月之暗面)",
        "url": "https://www.moonshot.cn/news",
        "kind": "list",
        "parser": "parse_moonshot_news",
        "country": "domestic",
        "timeout": 10,
        "verify": True,
    },
    {
        "name": "豆包 (Doubao)",
        "url": "https://www.doubao.com/update",
        "kind": "list",
        "parser": "parse_doubao_update",
        "country": "domestic",
        "timeout": 10,
        "verify": True,
    },
    {
        "name": "通义千问 (Qwen)",
        "url": "https://qwenlm.ai/blog/",
        "kind": "list",
        "parser": "parse_qwen_blog",
        "country": "domestic",
        "timeout": 10,
        "verify": False,
    },
    {
        "name": "xAI (Grok)",
        "url": "https://x.ai/blog",
        "kind": "list",
        "parser": "parse_xai_blog",
        "country": "foreign",
        "timeout": 15,
        "verify": False,
    },
    {
        "name": "Google Gemini",
        "url": "https://blog.google/technology/ai/",
        "kind": "list",
        "parser": "parse_google_gemini_blog",
        "country": "foreign",
        "timeout": 15,
        "verify": False,
    },
    {
        "name": "Perplexity AI",
        "url": "https://blog.perplexity.ai/",
        "kind": "list",
        "parser": "parse_perplexity_blog",
        "country": "foreign",
        "timeout": 15,
        "verify": False,
    },
]
